export type { AIProvider, AIProviderId, AIErrorKind, AIAttachment, DecideRequest, DecideResult, JsonRequest, ChatTurn, MealContext, MealImage, MealRecognition, RecognizedFood } from './types'
export { AIError, AI_ERROR_MESSAGES, isAIError } from './types'
export { MockProvider, MOCK_CHAT_REPLY, MOCK_UNCERTAINTY } from './mock'
export { AnthropicProvider, DEFAULT_ANTHROPIC_MODEL, MEAL_RECOGNITION_SCHEMA, parseMealRecognition, mapAnthropicError, toImageMediaType, stripDataUrl } from './anthropic'
export { GeminiProvider, DEFAULT_GEMINI_MODEL, mapGeminiError, parseGeminiResponse, toGeminiSchema } from './gemini'
export { configureAI, getProvider, recognizeMeal, coachChat, aiJson, aiDecide, aiConnected, isOnline, AI_TIMEOUT_MS, DECIDE_TIMEOUT_MS } from './gateway'
export type { ConfigureAIOptions, LedgerInput } from './gateway'
export * from './bridge'
