export { AppShell } from './AppShell'
export type { AppShellProps } from './AppShell'
export { TabBar, TABS, TAB_BAR_HEIGHT } from './TabBar'
export type { TabItem } from './TabBar'
export { QuickActions } from './QuickActions'
export type { QuickActionsProps } from './QuickActions'
export { Screen } from './Screen'
export type { ScreenProps } from './Screen'

export { Card } from './Card'
export type { CardProps, CardTone } from './Card'
export { Button } from './Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './Button'
export { IconButton } from './IconButton'
export type { IconButtonProps, IconButtonVariant, IconButtonSize } from './IconButton'
export { Sheet } from './Sheet'
export type { SheetProps } from './Sheet'

export { Field } from './Field'
export type { FieldProps } from './Field'
export { TextInput, INPUT_BASE } from './TextInput'
export type { TextInputProps } from './TextInput'
export { NumberInput } from './NumberInput'
export type { NumberInputProps } from './NumberInput'
export { Segmented } from './Segmented'
export type { SegmentedProps, SegmentedOption } from './Segmented'
export { Slider } from './Slider'
export type { SliderProps } from './Slider'
export { Stepper } from './Stepper'
export type { StepperProps } from './Stepper'
export { Chip } from './Chip'
export type { ChipProps } from './Chip'

export { StatusPill } from './StatusPill'
export type { StatusPillProps } from './StatusPill'
export { ReadinessBadge } from './ReadinessBadge'
export type { ReadinessBadgeProps } from './ReadinessBadge'
export { ProgressBar } from './ProgressBar'
export type { ProgressBarProps } from './ProgressBar'
export { MacroRow } from './MacroRow'
export type { MacroRowProps } from './MacroRow'
export { Sparkline } from './Sparkline'
export type { SparklineProps } from './Sparkline'
export { Stat } from './Stat'
export type { StatProps } from './Stat'

export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { LoadingState } from './LoadingState'
export type { LoadingStateProps } from './LoadingState'
export { ErrorState } from './ErrorState'
export type { ErrorStateProps } from './ErrorState'
export { OfflineBanner } from './OfflineBanner'
export type { OfflineBannerProps } from './OfflineBanner'
export { PermissionDenied } from './PermissionDenied'
export type { PermissionDeniedProps } from './PermissionDenied'

export { SectionHeader } from './SectionHeader'
export type { SectionHeaderProps } from './SectionHeader'
export { ListRow } from './ListRow'
export type { ListRowProps } from './ListRow'
export { Divider } from './Divider'
export type { DividerProps } from './Divider'

export { ToastProvider, useToast } from './Toast'
export type { ToastApi, ToastKind } from './Toast'

export { PILLARS, PILLAR_KEYS } from './pillars'
export type { Pillar, PillarKey, PillarMeta } from './pillars'
export { Ring } from './Ring'
export type { RingProps } from './Ring'
export { PillarDial } from './PillarDial'
export type { PillarDialProps, PillarDialItem } from './PillarDial'
export { ArcGauge } from './ArcGauge'
export type { ArcGaugeProps } from './ArcGauge'
export { HeroNumber } from './HeroNumber'
export type { HeroNumberProps } from './HeroNumber'
export { StatTile } from './StatTile'
export type { StatTileProps } from './StatTile'
export { LineChart } from './LineChart'
export type { LineChartProps, LineChartPoint } from './LineChart'
export { BarChart } from './BarChart'
export type { BarChartProps, BarChartBar } from './BarChart'
export { WeekStrip } from './WeekStrip'
export type { WeekStripProps, WeekStripDay, WeekStripState } from './WeekStrip'
export { RangeTabs } from './RangeTabs'
export type { RangeTabsProps } from './RangeTabs'
export { CoachQuote } from './CoachQuote'
export type { CoachQuoteProps } from './CoachQuote'
export { Skeleton } from './Skeleton'
export type { SkeletonProps } from './Skeleton'
export { Celebrate } from './Celebrate'
export type { CelebrateProps } from './Celebrate'
export { MoodSlider } from './MoodSlider'
export type { MoodSliderProps } from './MoodSlider'
export { BreathOrb } from './BreathOrb'
export type { BreathOrbProps, BreathPhase } from './BreathOrb'

export type { Tone } from './tones'
export { READINESS_TONE, TONE_SURFACE, TONE_TEXT, TONE_PILL, TONE_FILL } from './tones'
export { fmtInt, pct } from './util'

// v3 visual system (docs/DESIGN.md §10.2)
export { MuscleMap, muscleRegions, REGION_LABELS } from './MuscleMap'
export type { MuscleMapProps, RegionId } from './MuscleMap'
export { ExerciseVisual } from './ExerciseVisual'
export type { ExerciseVisualProps } from './ExerciseVisual'
export { FoodGlyph, foodIcon } from './FoodGlyph'
export type { FoodGlyphProps } from './FoodGlyph'
export { AIBadge } from './AIBadge'
export type { AIBadgeProps } from './AIBadge'
export { AIStatusChip } from './AIStatusChip'
export type { AIStatusChipProps } from './AIStatusChip'
export { Illustration } from './Illustration'
export type { IllustrationProps, IllustrationName } from './Illustration'
